theme: jekyll-theme-slate
html: <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <title>Our Menu</title>
    <style>
    * {
        box-sizing: border-box;
        
        
    }

    
    </style> 
        <link href="style/style.css" rel="stylesheet" type="text/css">
</head>

<body>
    <h1>Our Menu</h1>
    <div class="col-lg-4 col-md-12 col-sm-12">
       <div class="container">
         <p id="p1">Chicken</p>
          <p>lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do elusmod tempor incident ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commod
    o consequat.</p>
        </div>
    </div>
    <div class="col-lg-4 col-md-12 col-sm-12">
       <div class="container">
        <p id="p2">Beef</p>
         <p>lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do elusmod tempor incident ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commod
    o consequat.</p></div>
    </div>
    <div class="col-lg-4 col-md-12 col-sm-12">
       <div class="container">
        <p id="p3">Sushi</p>
        <p>lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do elusmod tempor incident ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commod
    o consequat.</p>
       </div>
    </div>
    
</body>
</html>
css: h1 {
    text-align: center;
    margin-bottom: 15px;
    margin-top: 15px;
    font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    font-size: 30px; 
}
body {
    background-color:white;
}

.container {
    border: 1px solid rgb(255, 255, 255);
    background-color: rgb(166, 167, 165);
    width: 90%;
    font-family: Arial, Helvetica, sans-serif;
    color: white;
    margin-right: 50px;
    margin-left: 50px;
    float: left; 
}
    

#p1 {
    background-color: rgba(250, 128, 114, 0.952);
    border: 1px solid black;
    float: right;
    padding: 10px;
    margin: auto;


}
#p2 {
    background-color: rgb(88, 134, 123);
    border: 1px solid black;
    float: right;
    padding: 10px;
    margin: auto;
}
#p3 {
    background-color: rgb(0, 129, 0);
    border: 1px solid black;
    float: right;
    padding: 10px;
    margin: auto;
    
}
p {
    margin-left: 10px;
    margin-right: 10px;
    clear: right;
}

/* Desktop View */

@media (min-width: 992px) {
  .col-lg-4 {
    float: left;
  }
  .col-lg-4 {
    width: 33%;
  }
}

/* Tablet View */

@media (min-width: 768px) and (max-width: 991px){
  .col-md-6 col-md-12 {
    float: left;
    width: 100%;
  }
   .col-md-6{
   width: 50%;
 }
  .col-md-12{
   width: 100%;
 }
}

/* Mobile View */

@media (max-width: 767px){
  .col-sm-12{
    width: 80%;
    float: left;
  }
}
